import Head from "next/head";
import Header from "../components/header/Header";
import Input from "../components/input/Input";
import Movies from "../components/movies/index";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>MovieUp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div></div>
      </main>
    </div>
  );
}
